#!/bin/sh
# Regenerates ios/Config.xcconfig from the repository-root .env.
#
# Xcode cannot read .env files, so the values are projected into an xcconfig
# that ios/project.yml already applies to the Honoured target. Android reads
# .env directly from Gradle and needs no generation step.

set -eu

ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/ios/Config.xcconfig"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: $ENV_FILE not found. Copy .env.example to .env first." >&2
  exit 1
fi

# Reads a KEY=value line, ignoring comments and surrounding whitespace.
read_env() {
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" | head -n 1
}

# `//` opens a comment in xcconfig files, so any value containing it (every
# https:// URL) must build the separator from a helper variable instead.
escape_slashes() {
  printf '%s' "$1" | sed 's|//|$(HONOURED_URL_SLASH)$(HONOURED_URL_SLASH)|g'
}

WEB_APP_URL="$(read_env HONOURED_WEB_APP_URL)"
IOS_API_KEY="$(read_env REVENUECAT_IOS_API_KEY)"
BUNDLE_ID="$(read_env IOS_BUNDLE_ID)"
TEAM_ID="$(read_env IOS_DEVELOPMENT_TEAM)"

if [ -z "$WEB_APP_URL" ]; then
  echo "error: HONOURED_WEB_APP_URL is empty in $ENV_FILE" >&2
  exit 1
fi

cat > "$OUT" <<EOF
// Generated by scripts/sync-env.sh from .env — do not edit by hand.
// Change .env and re-run the script instead.

HONOURED_URL_SLASH = /

HONOURED_WEB_APP_URL = $(escape_slashes "$WEB_APP_URL")
REVENUECAT_IOS_API_KEY = $IOS_API_KEY
HONOURED_BUNDLE_ID = $BUNDLE_ID
DEVELOPMENT_TEAM = $TEAM_ID
EOF

echo "wrote $OUT"
